### ISSUE TITLE
2019-08-30：单例面试考点

### ISSUE THREAD

**Issue by wxy520ll** [Moosphan/Android-Daily-Interview#135]
众所周知网上大部分的单例都是3种写法，面试官问了以下几个问题：

1.有没有其他的单例写法，这些单例写法的优缺点？如何攻破？

2.锁一个方法和锁一个this/class 有什么区别

答：锁一个方法，多线程情况下只允许一个线程访问此方法，但是可以允许多线程有多个对象的引入。锁一个对象，多线程情况下只允许一个线程能操作此对象。

**Comment by weikano** [comment]
enum方式
