### ISSUE TITLE
这两天面试滴滴，哈喽单车题目，已经挂了

### ISSUE THREAD

**Issue by feb07** [Moosphan/Android-Daily-Interview#206]
java基础
1、HashMap（哈希冲突），HashTable，ArrayList，LinkedList，BlockQueue等原理，插入等操作
2、GC机制（如果要自己设计回收机制，怎么设计）
3、23种设计模式，单例，观察者等设计模式，用过哪些，为什么这么用，有什么优势
4、线程池原理（线程核心数算法，线程复用原理）
5、synchronize，volatile等线程安全
6、多线程并发问题，线程与线程之间怎么通信
7、https原理、与http区别（CA证书怎么下发等）
8、排序算法
9、jvm，dalvik，ART区别
10、线程挂起原理

Android
1、apk生成流程
2、apk安装流程
3、handler，Loop，MessageQueue(怎么调度，设计)，thread
4、binder进程间通信
5、Android 四大组件为什么默认是在主线程
6、Android的编舞者Choreographer
7、MVC，MVP区别（MVC中activity把view抽离跟MVP的区别，P层怎么优化，回收，怎么解决P层跟V层的频繁调用）
8、app启动优化：必须初始化5个sdk，耗时10s，才进入主页，怎么优化到2s
9、模块间通信，怎么解决module之间耦合
10、自定义注解
11、weex解析js，渲染，数据绑定原理
12、Android Architecture
13、kotlin扩展函数，协程
14、JNI熟悉程度，使用
15、websocket通信，tcp(三次握手，四次握手) ，与udp区别
16、jsBridge原理，通信流程
17、为什么要组件化
18、Android领域最擅长做什么（一定要注意，不然会被问到死）
19、工作中最有挑战的点
20、Android中怎么传递字符流
21、Android系统里面有哪些东西（应用层，framework等）
22、内存泄露情况，以及优化
23、leakcanary原理，怎么分析
24、Android 屏幕刷新机制（16.6s）
25、EventBus源码
26、glide源码（缓存机制）
27、子module为什么用R2
28、看过哪些Android源码（一定要注意，不然会被问到死）
29、flutter用过吗
30、retrofit源码
31、获取view的宽高方法，view.post能获取，handler为什么不能获取

**Comment by Moosphan** [comment]
@feb07 多谢分享，祝好运😄

**Comment by NIKLINT** [comment]
也太难了吧，好多都是问源码的

**Comment by luckilyyg** [comment]
这是来自QQ邮箱的假期自动回复邮件。
